server.port: 8083

sidecar:
  hostname: ${SIDECAR_HOST:localhost}
  port: ${SIDECAR_PORT:6379}
  health-uri: ${SIDECAR_URI:http://localhost:8083/delegating-status}
  home-page-uri: ${SIDECAR_PAGE:http://localhost:8083/delegating-info}

script:
  health: ${HEALTH_SCRIPT:/tmp/health.groovy}

eureka:
  instance:
    preferIpAddress: true
    metadata-map:
      app-type: "general"
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka/}

info:
  app:
    name: script-sidecar
    description: Common sidecar
    version: "@project.version@"
